function dpsidt = MS_gate_fun_OR_ideal(t,psi,qudit_level,gate_time,n_cycle,eta_COM,w_COM,w_Tilt,w_split,Omega_bar,...
    Cfactor,State_raise,State_lower,State_I,Motion_raise_COM,Motion_lower_COM,...
    Motion_raise_Tilt,Motion_lower_Tilt)

%delta=2.*pi.*5.01; %Laser detuning
delta=w_COM+n_cycle*2*pi/gate_time;
eta_Tilt=eta_COM*sqrt(w_COM/w_Tilt);
detuning=abs(4*w_split-delta);
detuning2=abs(4*w_split+delta);

Motion_factor_state_raise_COM(:,:,1:2:qudit_level)=repmat(expm(-(-1^((qudit_level-1)/2)).*1i.*eta_COM.*(exp(1i.*w_COM.*t).*Motion_raise_COM+exp(-1i.*w_COM.*t).*Motion_lower_COM)),[1 1 numel(1:2:qudit_level)]);
Motion_factor_state_raise_COM(:,:,2:2:(qudit_level-1))=repmat(expm((-1^((qudit_level-1)/2)).*1i.*eta_COM.*(exp(1i.*w_COM.*t).*Motion_raise_COM+exp(-1i.*w_COM.*t).*Motion_lower_COM)),[1 1 numel(2:2:(qudit_level-1))]);
Motion_factor_state_lower_COM(:,:,1:2:qudit_level)=repmat(expm((-1^((qudit_level-1)/2)).*1i.*eta_COM.*(exp(1i.*w_COM.*t).*Motion_raise_COM+exp(-1i.*w_COM.*t).*Motion_lower_COM)),[1 1 numel(1:2:qudit_level)]);
Motion_factor_state_lower_COM(:,:,2:2:(qudit_level-1))=repmat(expm(-(-1^((qudit_level-1)/2)).*1i.*eta_COM.*(exp(1i.*w_COM.*t).*Motion_raise_COM+exp(-1i.*w_COM.*t).*Motion_lower_COM)),[1 1 numel(2:2:(qudit_level-1))]);
Motion_factor_state_raise_Tilt(:,:,1:2:qudit_level)=repmat(expm(-(-1^((qudit_level-1)/2)).*1i.*eta_Tilt.*(exp(1i.*w_Tilt.*t).*Motion_raise_Tilt+exp(-1i.*w_Tilt.*t).*Motion_lower_Tilt)),[1 1 numel(1:2:qudit_level)]);
Motion_factor_state_raise_Tilt(:,:,2:2:(qudit_level-1))=repmat(expm((-1^((qudit_level-1)/2)).*1i.*eta_Tilt.*(exp(1i.*w_Tilt.*t).*Motion_raise_Tilt+exp(-1i.*w_Tilt.*t).*Motion_lower_Tilt)),[1 1 numel(2:2:(qudit_level-1))]);
Motion_factor_state_lower_Tilt(:,:,1:2:qudit_level)=repmat(expm((-1^((qudit_level-1)/2)).*1i.*eta_Tilt.*(exp(1i.*w_Tilt.*t).*Motion_raise_Tilt+exp(-1i.*w_Tilt.*t).*Motion_lower_Tilt)),[1 1 numel(1:2:qudit_level)]);
Motion_factor_state_lower_Tilt(:,:,2:2:(qudit_level-1))=repmat(expm(-(-1^((qudit_level-1)/2)).*1i.*eta_Tilt.*(exp(1i.*w_Tilt.*t).*Motion_raise_Tilt+exp(-1i.*w_Tilt.*t).*Motion_lower_Tilt)),[1 1 numel(2:2:(qudit_level-1))]);
M_evol_array=nan(numel(psi),numel(psi),qudit_level-1);
for qq=1:qudit_level-1
    %{
    M_evol_array(:,:,qq)=-1i.*Omega_bar.*cos(delta.*t).*...
        (kron(kron(State_raise(:,:,qq),State_I),kron(Motion_factor_state_raise_COM(:,:,qq),Motion_I_Tilt))...
        +kron(kron(State_I,State_raise(:,:,qq)),kron(Motion_factor_state_raise_COM(:,:,qq),Motion_I_Tilt))...
        +kron(kron(State_lower(:,:,qq),State_I),kron(Motion_factor_state_lower_COM(:,:,qq),Motion_I_Tilt))...
        +kron(kron(State_I,State_lower(:,:,qq)),kron(Motion_factor_state_lower_COM(:,:,qq),Motion_I_Tilt))...
        +kron(kron(State_raise(:,:,qq),State_I),kron(Motion_I_COM,Motion_factor_state_raise_Tilt(:,:,qq)))...
        +kron(kron(State_I,State_raise(:,:,qq)),kron(Motion_I_COM,Motion_factor_state_lower_Tilt(:,:,qq)))...
        +kron(kron(State_lower(:,:,qq),State_I),kron(Motion_I_COM,Motion_factor_state_lower_Tilt(:,:,qq)))...
        +kron(kron(State_I,State_lower(:,:,qq)),kron(Motion_I_COM,Motion_factor_state_raise_Tilt(:,:,qq))));
    %}
    l=qq-ceil(qudit_level/2);
    
    %{
    %H_OR=(Cfactor(qq).*Omega_bar./2).*(exp(-((-1)^l)*1i*(-((-1)^l).*detuning*t-pi/2)).*kron(kron(State_raise(:,:,qq),State_I),kron(Motion_factor_state_raise_COM(:,:,qq),Motion_factor_state_raise_Tilt(:,:,qq)))...
    %    +exp(-((-1)^l)*1i*(-((-1)^l).*detuning*t-pi/2)).*kron(kron(State_I,State_raise(:,:,qq)),kron(Motion_factor_state_raise_COM(:,:,qq),Motion_factor_state_lower_Tilt(:,:,qq)))...
    %    +exp(((-1)^l)*1i*(-((-1)^l).*detuning*t-pi/2)).*kron(kron(State_lower(:,:,qq),State_I),kron(Motion_factor_state_lower_COM(:,:,qq),Motion_factor_state_lower_Tilt(:,:,qq)))...
    %    +exp(((-1)^l)*1i*(-((-1)^l).*detuning*t-pi/2)).*kron(kron(State_I,State_lower(:,:,qq)),kron(Motion_factor_state_lower_COM(:,:,qq),Motion_factor_state_raise_Tilt(:,:,qq))));
    H_OR=(Cfactor(qq).*Omega_bar./2).*(exp(1i*(detuning*t+((-1)^l)*pi/2)).*kron(kron(State_raise(:,:,qq),State_I),kron(diag(ones(10,1)),diag(ones(3,1))))...
        +exp(1i*(detuning*t+((-1)^l)*pi/2)).*kron(kron(State_I,State_raise(:,:,qq)),kron(diag(ones(10,1)),diag(ones(3,1))))...
        +exp(1i*(-detuning*t-((-1)^l)*pi/2)).*kron(kron(State_lower(:,:,qq),State_I),kron(diag(ones(10,1)),diag(ones(3,1))))...
        +exp(1i*(-detuning*t-((-1)^l)*pi/2)).*kron(kron(State_I,State_lower(:,:,qq)),kron(diag(ones(10,1)),diag(ones(3,1)))));
    %H_OR=(Cfactor(qq).*Omega_bar).*cos(detuning.*t).*(((-1)^l).*1i.*kron(kron(State_raise(:,:,qq),State_I),kron(diag(ones(10,1)),diag(ones(3,1))))...
    %    +((-1)^l).*1i.*kron(kron(State_I,State_raise(:,:,qq)),kron(diag(ones(10,1)),diag(ones(3,1))))...
    %    -((-1)^l).*1i.*kron(kron(State_lower(:,:,qq),State_I),kron(diag(ones(10,1)),diag(ones(3,1))))...
    %    -((-1)^l).*1i.*kron(kron(State_I,State_lower(:,:,qq)),kron(diag(ones(10,1)),diag(ones(3,1)))));
    %}
    
    if qq==1 || qq==2
    H_OR=(Cfactor(qq).*Omega_bar./2).*(exp(-((-1)^l)*1i*(-detuning*t-pi/2)).*kron(kron(State_raise(:,:,qq),State_I),kron(diag(ones(size(Motion_raise_COM,1),1)),diag(ones(size(Motion_raise_Tilt,1),1))))...
        +exp(-((-1)^l)*1i*(-detuning*t-pi/2)).*kron(kron(State_I,State_raise(:,:,qq)),kron(diag(ones(size(Motion_raise_COM,1),1)),diag(ones(size(Motion_raise_Tilt,1),1))))...
        +exp(((-1)^l)*1i*(-detuning*t-pi/2)).*kron(kron(State_lower(:,:,qq),State_I),kron(diag(ones(size(Motion_raise_COM,1),1)),diag(ones(size(Motion_raise_Tilt,1),1))))...
        +exp(((-1)^l)*1i*(-detuning*t-pi/2)).*kron(kron(State_I,State_lower(:,:,qq)),kron(diag(ones(size(Motion_raise_COM,1),1)),diag(ones(size(Motion_raise_Tilt,1),1)))))...
        +(Cfactor(qq).*Omega_bar./2).*(exp(-((-1)^l)*1i*(-detuning2*t-pi/2)).*kron(kron(State_raise(:,:,qq),State_I),kron(diag(ones(size(Motion_raise_COM,1),1)),diag(ones(size(Motion_raise_Tilt,1),1))))...
        +exp(-((-1)^l)*1i*(-detuning2*t-pi/2)).*kron(kron(State_I,State_raise(:,:,qq)),kron(diag(ones(size(Motion_raise_COM,1),1)),diag(ones(size(Motion_raise_Tilt,1),1))))...
        +exp(((-1)^l)*1i*(-detuning2*t-pi/2)).*kron(kron(State_lower(:,:,qq),State_I),kron(diag(ones(size(Motion_raise_COM,1),1)),diag(ones(size(Motion_raise_Tilt,1),1))))...
        +exp(((-1)^l)*1i*(-detuning2*t-pi/2)).*kron(kron(State_I,State_lower(:,:,qq)),kron(diag(ones(size(Motion_raise_COM,1),1)),diag(ones(size(Motion_raise_Tilt,1),1)))));
    else
    H_OR=(Cfactor(qq).*Omega_bar./2).*(exp(-((-1)^l)*1i*(detuning*t-pi/2)).*kron(kron(State_raise(:,:,qq),State_I),kron(diag(ones(size(Motion_raise_COM,1),1)),diag(ones(size(Motion_raise_Tilt,1),1))))...
        +exp(-((-1)^l)*1i*(detuning*t-pi/2)).*kron(kron(State_I,State_raise(:,:,qq)),kron(diag(ones(size(Motion_raise_COM,1),1)),diag(ones(size(Motion_raise_Tilt,1),1))))...
        +exp(((-1)^l)*1i*(detuning*t-pi/2)).*kron(kron(State_lower(:,:,qq),State_I),kron(diag(ones(size(Motion_raise_COM,1),1)),diag(ones(size(Motion_raise_Tilt,1),1))))...
        +exp(((-1)^l)*1i*(detuning*t-pi/2)).*kron(kron(State_I,State_lower(:,:,qq)),kron(diag(ones(size(Motion_raise_COM,1),1)),diag(ones(size(Motion_raise_Tilt,1),1)))))...
        +(Cfactor(qq).*Omega_bar./2).*(exp(-((-1)^l)*1i*(detuning2*t-pi/2)).*kron(kron(State_raise(:,:,qq),State_I),kron(diag(ones(size(Motion_raise_COM,1),1)),diag(ones(size(Motion_raise_Tilt,1),1))))...
        +exp(-((-1)^l)*1i*(detuning2*t-pi/2)).*kron(kron(State_I,State_raise(:,:,qq)),kron(diag(ones(size(Motion_raise_COM,1),1)),diag(ones(size(Motion_raise_Tilt,1),1))))...
        +exp(((-1)^l)*1i*(detuning2*t-pi/2)).*kron(kron(State_lower(:,:,qq),State_I),kron(diag(ones(size(Motion_raise_COM,1),1)),diag(ones(size(Motion_raise_Tilt,1),1))))...
        +exp(((-1)^l)*1i*(detuning2*t-pi/2)).*kron(kron(State_I,State_lower(:,:,qq)),kron(diag(ones(size(Motion_raise_COM,1),1)),diag(ones(size(Motion_raise_Tilt,1),1)))));
    end
    
    M_evol_array(:,:,qq)=-1i.*eta_COM.*(Omega_bar/2).*...
        (kron(kron(State_raise(:,:,qq),State_I),kron(exp(1i.*(w_COM-delta).*t).*Motion_raise_COM+exp(-1i.*(w_COM-delta).*t).*Motion_lower_COM,diag(ones(size(Motion_raise_Tilt,1),1))))...
        +kron(kron(State_I,State_raise(:,:,qq)),kron(exp(1i.*(w_COM-delta).*t).*Motion_raise_COM+exp(-1i.*(w_COM-delta).*t).*Motion_lower_COM,diag(ones(size(Motion_raise_Tilt,1),1))))...
        +kron(kron(State_lower(:,:,qq),State_I),kron(exp(1i.*(w_COM-delta).*t).*Motion_raise_COM+exp(-1i.*(w_COM-delta).*t).*Motion_lower_COM,diag(ones(size(Motion_raise_Tilt,1),1))))...
        +kron(kron(State_I,State_lower(:,:,qq)),kron(exp(1i.*(w_COM-delta).*t).*Motion_raise_COM+exp(-1i.*(w_COM-delta).*t).*Motion_lower_COM,diag(ones(size(Motion_raise_Tilt,1),1)))))...
        -1i.*H_OR;
        %-1i.*Cfactor(qq).*(Omega_bar/2).*((cos(detuning.*t)-1i.*sin(detuning.*t)).*...
        %(kron(kron(State_raise(:,:,qq),State_I),kron(diag(ones(10,1)),diag(ones(3,1))))...
        %+kron(kron(State_I,State_raise(:,:,qq)),kron(diag(ones(10,1)),diag(ones(3,1)))))...
        %+(cos(detuning.*t)-1i.*sin(detuning.*t)).*(kron(kron(State_lower(:,:,qq),State_I),kron(diag(ones(10,1)),diag(ones(3,1))))...
        %+kron(kron(State_I,State_lower(:,:,qq)),kron(diag(ones(10,1)),diag(ones(3,1))))));
end
M_evol=sum(M_evol_array,3);
dpsidt=M_evol*psi;