function dpsidt = MS_gate_fun_mag_shift(t,psi,qudit_level,gate_time,n_cycle,eta_COM,w_COM,w_Tilt,Omega_bar,...
    State_raise,State_lower,State_I,Motion_raise_COM,Motion_lower_COM,...
    Motion_raise_Tilt,Motion_lower_Tilt,State_mag_shift)

%delta=2.*pi.*5.01; %Laser detuning
delta=w_COM+n_cycle*2*pi/gate_time;
eta_Tilt=eta_COM*sqrt(w_COM/w_Tilt);

Motion_factor_state_raise_COM(:,:,1:2:qudit_level)=repmat(expm(-(-1^((qudit_level-1)/2)).*1i.*eta_COM.*(exp(1i.*w_COM.*t).*Motion_raise_COM+exp(-1i.*w_COM.*t).*Motion_lower_COM)),[1 1 numel(1:2:qudit_level)]);
Motion_factor_state_raise_COM(:,:,2:2:(qudit_level-1))=repmat(expm((-1^((qudit_level-1)/2)).*1i.*eta_COM.*(exp(1i.*w_COM.*t).*Motion_raise_COM+exp(-1i.*w_COM.*t).*Motion_lower_COM)),[1 1 numel(2:2:(qudit_level-1))]);
Motion_factor_state_lower_COM(:,:,1:2:qudit_level)=repmat(expm((-1^((qudit_level-1)/2)).*1i.*eta_COM.*(exp(1i.*w_COM.*t).*Motion_raise_COM+exp(-1i.*w_COM.*t).*Motion_lower_COM)),[1 1 numel(1:2:qudit_level)]);
Motion_factor_state_lower_COM(:,:,2:2:(qudit_level-1))=repmat(expm(-(-1^((qudit_level-1)/2)).*1i.*eta_COM.*(exp(1i.*w_COM.*t).*Motion_raise_COM+exp(-1i.*w_COM.*t).*Motion_lower_COM)),[1 1 numel(2:2:(qudit_level-1))]);
Motion_factor_state_raise_Tilt(:,:,1:2:qudit_level)=repmat(expm(-(-1^((qudit_level-1)/2)).*1i.*eta_Tilt.*(exp(1i.*w_Tilt.*t).*Motion_raise_Tilt+exp(-1i.*w_Tilt.*t).*Motion_lower_Tilt)),[1 1 numel(1:2:qudit_level)]);
Motion_factor_state_raise_Tilt(:,:,2:2:(qudit_level-1))=repmat(expm((-1^((qudit_level-1)/2)).*1i.*eta_Tilt.*(exp(1i.*w_Tilt.*t).*Motion_raise_Tilt+exp(-1i.*w_Tilt.*t).*Motion_lower_Tilt)),[1 1 numel(2:2:(qudit_level-1))]);
Motion_factor_state_lower_Tilt(:,:,1:2:qudit_level)=repmat(expm((-1^((qudit_level-1)/2)).*1i.*eta_Tilt.*(exp(1i.*w_Tilt.*t).*Motion_raise_Tilt+exp(-1i.*w_Tilt.*t).*Motion_lower_Tilt)),[1 1 numel(1:2:qudit_level)]);
Motion_factor_state_lower_Tilt(:,:,2:2:(qudit_level-1))=repmat(expm(-(-1^((qudit_level-1)/2)).*1i.*eta_Tilt.*(exp(1i.*w_Tilt.*t).*Motion_raise_Tilt+exp(-1i.*w_Tilt.*t).*Motion_lower_Tilt)),[1 1 numel(2:2:(qudit_level-1))]);
M_evol_array=nan(numel(psi),numel(psi),qudit_level-1);
for qq=1:qudit_level-1
    %{
    M_evol_array(:,:,qq)=-1i.*Omega_bar.*cos(delta.*t).*...
        (kron(kron(State_raise(:,:,qq),State_I),kron(Motion_factor_state_raise_COM(:,:,qq),Motion_I_Tilt))...
        +kron(kron(State_I,State_raise(:,:,qq)),kron(Motion_factor_state_raise_COM(:,:,qq),Motion_I_Tilt))...
        +kron(kron(State_lower(:,:,qq),State_I),kron(Motion_factor_state_lower_COM(:,:,qq),Motion_I_Tilt))...
        +kron(kron(State_I,State_lower(:,:,qq)),kron(Motion_factor_state_lower_COM(:,:,qq),Motion_I_Tilt))...
        +kron(kron(State_raise(:,:,qq),State_I),kron(Motion_I_COM,Motion_factor_state_raise_Tilt(:,:,qq)))...
        +kron(kron(State_I,State_raise(:,:,qq)),kron(Motion_I_COM,Motion_factor_state_lower_Tilt(:,:,qq)))...
        +kron(kron(State_lower(:,:,qq),State_I),kron(Motion_I_COM,Motion_factor_state_lower_Tilt(:,:,qq)))...
        +kron(kron(State_I,State_lower(:,:,qq)),kron(Motion_I_COM,Motion_factor_state_raise_Tilt(:,:,qq))));
    %}
    l=qq-ceil(qudit_level/2);
    M_evol_array(:,:,qq)=-1i.*Omega_bar.*cos(delta.*t).*...
        (kron(kron(((-1).^l).*1i.*State_raise(:,:,qq),State_I),kron(Motion_factor_state_raise_COM(:,:,qq),Motion_factor_state_raise_Tilt(:,:,qq)))...
        +kron(kron(State_I,((-1).^l).*1i.*State_raise(:,:,qq)),kron(Motion_factor_state_raise_COM(:,:,qq),Motion_factor_state_lower_Tilt(:,:,qq)))...
        +kron(kron(-((-1).^l).*1i.*State_lower(:,:,qq),State_I),kron(Motion_factor_state_lower_COM(:,:,qq),Motion_factor_state_lower_Tilt(:,:,qq)))...
        +kron(kron(State_I,-((-1).^l).*1i.*State_lower(:,:,qq)),kron(Motion_factor_state_lower_COM(:,:,qq),Motion_factor_state_raise_Tilt(:,:,qq))));
end
M_evol=sum(M_evol_array,3);
M_evol=M_evol+kron(kron(State_mag_shift,State_I),kron(diag(ones(size(Motion_raise_COM,1),1)),diag(ones(size(Motion_raise_Tilt,1),1))))...
    +kron(kron(State_I,State_mag_shift),kron(diag(ones(size(Motion_raise_COM,1),1)),diag(ones(size(Motion_raise_Tilt,1),1))));
dpsidt=M_evol*psi;